CREATE TABLE IF NOT EXISTS ciudades (
  id INTEGER PRIMARY KEY,
  nombre TEXT NOT NULL UNIQUE,
  departamento TEXT
);

INSERT INTO ciudades (nombre, departamento) VALUES ('Abancay', 'Apurímac');
INSERT INTO ciudades (nombre, departamento) VALUES ('Amazonas', 'Amazonas');
INSERT INTO ciudades (nombre, departamento) VALUES ('Áncash', 'Áncash');
INSERT INTO ciudades (nombre, departamento) VALUES ('Andahuaylas', 'Apurímac');
INSERT INTO ciudades (nombre, departamento) VALUES ('Apurímac', 'Apurímac');
INSERT INTO ciudades (nombre, departamento) VALUES ('Arequipa', 'Arequipa');
INSERT INTO ciudades (nombre, departamento) VALUES ('Ate', 'Lima');
INSERT INTO ciudades (nombre, departamento) VALUES ('Ayacucho', 'Ayacucho');
INSERT INTO ciudades (nombre, departamento) VALUES ('Ayaviri', 'Puno');
INSERT INTO ciudades (nombre, departamento) VALUES ('Bagua', 'Amazonas');
INSERT INTO ciudades (nombre, departamento) VALUES ('Bagua Grande', 'Amazonas');
INSERT INTO ciudades (nombre, departamento) VALUES ('Barranca', 'Lima');
INSERT INTO ciudades (nombre, departamento) VALUES ('Barranco', 'Lima');
INSERT INTO ciudades (nombre, departamento) VALUES ('Bellavista', 'Callao');
INSERT INTO ciudades (nombre, departamento) VALUES ('Breña', 'Lima');
INSERT INTO ciudades (nombre, departamento) VALUES ('Cajabamba', 'Cajamarca');
INSERT INTO ciudades (nombre, departamento) VALUES ('Cajamarca', 'Cajamarca');
INSERT INTO ciudades (nombre, departamento) VALUES ('Callao', 'Callao');
INSERT INTO ciudades (nombre, departamento) VALUES ('Camaná', 'Arequipa');
INSERT INTO ciudades (nombre, departamento) VALUES ('Cañete', 'Lima');
INSERT INTO ciudades (nombre, departamento) VALUES ('Carabayllo', 'Lima');
INSERT INTO ciudades (nombre, departamento) VALUES ('Caraz', 'Áncash');
INSERT INTO ciudades (nombre, departamento) VALUES ('Carmen de la Legua', 'Callao');
INSERT INTO ciudades (nombre, departamento) VALUES ('Casma', 'Áncash');
INSERT INTO ciudades (nombre, departamento) VALUES ('Catacaos', 'Piura');
INSERT INTO ciudades (nombre, departamento) VALUES ('Cerro de Pasco', 'Pasco');
INSERT INTO ciudades (nombre, departamento) VALUES ('Chachapoyas', 'Amazonas');
INSERT INTO ciudades (nombre, departamento) VALUES ('Chanchamayo', 'Junín');
INSERT INTO ciudades (nombre, departamento) VALUES ('Chepén', 'La Libertad');
INSERT INTO ciudades (nombre, departamento) VALUES ('Chiclayo', 'Lambayeque');
INSERT INTO ciudades (nombre, departamento) VALUES ('Chimbote', 'Áncash');
INSERT INTO ciudades (nombre, departamento) VALUES ('Chincha Alta', 'Ica');
INSERT INTO ciudades (nombre, departamento) VALUES ('Chorrillos', 'Lima');
INSERT INTO ciudades (nombre, departamento) VALUES ('Chosica', 'Lima');
INSERT INTO ciudades (nombre, departamento) VALUES ('Chota', 'Cajamarca');
INSERT INTO ciudades (nombre, departamento) VALUES ('Chulucanas', 'Piura');
INSERT INTO ciudades (nombre, departamento) VALUES ('Cieneguilla', 'Lima');
INSERT INTO ciudades (nombre, departamento) VALUES ('Comas', 'Lima');
INSERT INTO ciudades (nombre, departamento) VALUES ('Cusco', 'Cusco');
INSERT INTO ciudades (nombre, departamento) VALUES ('Desaguadero', 'Puno');
INSERT INTO ciudades (nombre, departamento) VALUES ('El Agustino', 'Lima');
INSERT INTO ciudades (nombre, departamento) VALUES ('Ferreñafe', 'Lambayeque');
INSERT INTO ciudades (nombre, departamento) VALUES ('Huacho', 'Lima');
INSERT INTO ciudades (nombre, departamento) VALUES ('Huamachuco', 'La Libertad');
INSERT INTO ciudades (nombre, departamento) VALUES ('Huancavelica', 'Huancavelica');
INSERT INTO ciudades (nombre, departamento) VALUES ('Huancayo', 'Junín');
INSERT INTO ciudades (nombre, departamento) VALUES ('Huánuco', 'Huánuco');
INSERT INTO ciudades (nombre, departamento) VALUES ('Huaral', 'Lima');
INSERT INTO ciudades (nombre, departamento) VALUES ('Huaraz', 'Áncash');
INSERT INTO ciudades (nombre, departamento) VALUES ('Huarmey', 'Áncash');
INSERT INTO ciudades (nombre, departamento) VALUES ('Ica', 'Ica');
INSERT INTO ciudades (nombre, departamento) VALUES ('Ilave', 'Puno');
INSERT INTO ciudades (nombre, departamento) VALUES ('Ilo', 'Moquegua');
INSERT INTO ciudades (nombre, departamento) VALUES ('Independencia', 'Lima');
INSERT INTO ciudades (nombre, departamento) VALUES ('Iquitos', 'Loreto');
INSERT INTO ciudades (nombre, departamento) VALUES ('Jaén', 'Cajamarca');
INSERT INTO ciudades (nombre, departamento) VALUES ('Jauja', 'Junín');
INSERT INTO ciudades (nombre, departamento) VALUES ('Jesús María', 'Lima');
INSERT INTO ciudades (nombre, departamento) VALUES ('Juanjuí', 'San Martín');
INSERT INTO ciudades (nombre, departamento) VALUES ('Juliaca', 'Puno');
INSERT INTO ciudades (nombre, departamento) VALUES ('Junín', 'Junín');
INSERT INTO ciudades (nombre, departamento) VALUES ('La Libertad', 'La Libertad');
INSERT INTO ciudades (nombre, departamento) VALUES ('La Merced', 'Junín');
INSERT INTO ciudades (nombre, departamento) VALUES ('La Molina', 'Lima');
INSERT INTO ciudades (nombre, departamento) VALUES ('La Oroya', 'Junín');
INSERT INTO ciudades (nombre, departamento) VALUES ('La Perla', 'Callao');
INSERT INTO ciudades (nombre, departamento) VALUES ('La Punta', 'Callao');
INSERT INTO ciudades (nombre, departamento) VALUES ('La Victoria', 'Lima');
INSERT INTO ciudades (nombre, departamento) VALUES ('Lamas', 'San Martín');
INSERT INTO ciudades (nombre, departamento) VALUES ('Lambayeque', 'Lambayeque');
INSERT INTO ciudades (nombre, departamento) VALUES ('Lima', 'Lima');
INSERT INTO ciudades (nombre, departamento) VALUES ('Lince', 'Lima');
INSERT INTO ciudades (nombre, departamento) VALUES ('Loreto', 'Loreto');
INSERT INTO ciudades (nombre, departamento) VALUES ('Los Olivos', 'Lima');
INSERT INTO ciudades (nombre, departamento) VALUES ('Lurín', 'Lima');
INSERT INTO ciudades (nombre, departamento) VALUES ('Madre de Dios', 'Madre de Dios');
INSERT INTO ciudades (nombre, departamento) VALUES ('Magdalena del Mar', 'Lima');
INSERT INTO ciudades (nombre, departamento) VALUES ('Miraflores', 'Lima');
INSERT INTO ciudades (nombre, departamento) VALUES ('Mollendo', 'Arequipa');
INSERT INTO ciudades (nombre, departamento) VALUES ('Moquegua', 'Moquegua');
INSERT INTO ciudades (nombre, departamento) VALUES ('Motupe', 'Lambayeque');
INSERT INTO ciudades (nombre, departamento) VALUES ('Moyobamba', 'San Martín');
INSERT INTO ciudades (nombre, departamento) VALUES ('Nazca', 'Ica');
INSERT INTO ciudades (nombre, departamento) VALUES ('Olmos', 'Lambayeque');
INSERT INTO ciudades (nombre, departamento) VALUES ('Pacasmayo', 'La Libertad');
INSERT INTO ciudades (nombre, departamento) VALUES ('Pachacámac', 'Lima');
INSERT INTO ciudades (nombre, departamento) VALUES ('Paita', 'Piura');
INSERT INTO ciudades (nombre, departamento) VALUES ('Pasco', 'Pasco');
INSERT INTO ciudades (nombre, departamento) VALUES ('Pisco', 'Ica');
INSERT INTO ciudades (nombre, departamento) VALUES ('Piura', 'Piura');
INSERT INTO ciudades (nombre, departamento) VALUES ('Pucallpa', 'Ucayali');
INSERT INTO ciudades (nombre, departamento) VALUES ('Pueblo Libre', 'Lima');
INSERT INTO ciudades (nombre, departamento) VALUES ('Puente Piedra', 'Lima');
INSERT INTO ciudades (nombre, departamento) VALUES ('Puerto Maldonado', 'Madre de Dios');
INSERT INTO ciudades (nombre, departamento) VALUES ('Puno', 'Puno');
INSERT INTO ciudades (nombre, departamento) VALUES ('Quillabamba', 'Cusco');
INSERT INTO ciudades (nombre, departamento) VALUES ('Rímac', 'Lima');
INSERT INTO ciudades (nombre, departamento) VALUES ('San Borja', 'Lima');
INSERT INTO ciudades (nombre, departamento) VALUES ('San Isidro', 'Lima');
INSERT INTO ciudades (nombre, departamento) VALUES ('San Juan de Lurigancho', 'Lima');
INSERT INTO ciudades (nombre, departamento) VALUES ('San Juan de Miraflores', 'Lima');
INSERT INTO ciudades (nombre, departamento) VALUES ('San Luis', 'Lima');
INSERT INTO ciudades (nombre, departamento) VALUES ('San Martín', 'San Martín');
INSERT INTO ciudades (nombre, departamento) VALUES ('San Martín de Porres', 'Lima');
INSERT INTO ciudades (nombre, departamento) VALUES ('San Miguel', 'Lima');
INSERT INTO ciudades (nombre, departamento) VALUES ('Santa Anita', 'Lima');
INSERT INTO ciudades (nombre, departamento) VALUES ('Santiago de Surco', 'Lima');
INSERT INTO ciudades (nombre, departamento) VALUES ('Satipo', 'Junín');
INSERT INTO ciudades (nombre, departamento) VALUES ('Sechura', 'Piura');
INSERT INTO ciudades (nombre, departamento) VALUES ('Sicuani', 'Cusco');
INSERT INTO ciudades (nombre, departamento) VALUES ('Sullana', 'Piura');
INSERT INTO ciudades (nombre, departamento) VALUES ('Surquillo', 'Lima');
INSERT INTO ciudades (nombre, departamento) VALUES ('Tacna', 'Tacna');
INSERT INTO ciudades (nombre, departamento) VALUES ('Talara', 'Piura');
INSERT INTO ciudades (nombre, departamento) VALUES ('Tarapoto', 'San Martín');
INSERT INTO ciudades (nombre, departamento) VALUES ('Tarma', 'Junín');
INSERT INTO ciudades (nombre, departamento) VALUES ('Tingo María', 'Huánuco');
INSERT INTO ciudades (nombre, departamento) VALUES ('Trujillo', 'La Libertad');
INSERT INTO ciudades (nombre, departamento) VALUES ('Tumbes', 'Tumbes');
INSERT INTO ciudades (nombre, departamento) VALUES ('Ucayali', 'Ucayali');
INSERT INTO ciudades (nombre, departamento) VALUES ('Ventanilla', 'Callao');
INSERT INTO ciudades (nombre, departamento) VALUES ('Villa El Salvador', 'Lima');
INSERT INTO ciudades (nombre, departamento) VALUES ('Villa María del Triunfo', 'Lima');
INSERT INTO ciudades (nombre, departamento) VALUES ('Yungay', 'Áncash');
INSERT INTO ciudades (nombre, departamento) VALUES ('Yurimaguas', 'Loreto');
