package db

// CiudadesPeru es el dataset real que se carga en la base de datos: capitales
// departamentales, principales ciudades de provincia y distritos de Lima/Callao.
// Sirve como fuente de datos para el autocompletado del Radix Trie.
var CiudadesPeru = []Ciudad{
	// Capitales departamentales y ciudades principales
	{"Lima", "Lima"},
	{"Arequipa", "Arequipa"},
	{"Trujillo", "La Libertad"},
	{"Chiclayo", "Lambayeque"},
	{"Piura", "Piura"},
	{"Iquitos", "Loreto"},
	{"Cusco", "Cusco"},
	{"Chimbote", "Áncash"},
	{"Huancayo", "Junín"},
	{"Tacna", "Tacna"},
	{"Juliaca", "Puno"},
	{"Ica", "Ica"},
	{"Cajamarca", "Cajamarca"},
	{"Pucallpa", "Ucayali"},
	{"Sullana", "Piura"},
	{"Ayacucho", "Ayacucho"},
	{"Chincha Alta", "Ica"},
	{"Huánuco", "Huánuco"},
	{"Tarapoto", "San Martín"},
	{"Puno", "Puno"},
	{"Tumbes", "Tumbes"},
	{"Talara", "Piura"},
	{"Huaraz", "Áncash"},
	{"Cerro de Pasco", "Pasco"},
	{"Moquegua", "Moquegua"},
	{"Abancay", "Apurímac"},
	{"Moyobamba", "San Martín"},
	{"Puerto Maldonado", "Madre de Dios"},
	{"Huancavelica", "Huancavelica"},
	{"Chachapoyas", "Amazonas"},

	// Otras ciudades de provincia
	{"Cañete", "Lima"},
	{"Barranca", "Lima"},
	{"Huacho", "Lima"},
	{"Huaral", "Lima"},
	{"Chosica", "Lima"},
	{"Nazca", "Ica"},
	{"Pisco", "Ica"},
	{"Mollendo", "Arequipa"},
	{"Camaná", "Arequipa"},
	{"Ilo", "Moquegua"},
	{"Sicuani", "Cusco"},
	{"Quillabamba", "Cusco"},
	{"Andahuaylas", "Apurímac"},
	{"Jaén", "Cajamarca"},
	{"Cajabamba", "Cajamarca"},
	{"Chota", "Cajamarca"},
	{"Bagua", "Amazonas"},
	{"Bagua Grande", "Amazonas"},
	{"Tarma", "Junín"},
	{"La Oroya", "Junín"},
	{"Jauja", "Junín"},
	{"Satipo", "Junín"},
	{"La Merced", "Junín"},
	{"Chanchamayo", "Junín"},
	{"Yurimaguas", "Loreto"},
	{"Tingo María", "Huánuco"},
	{"Catacaos", "Piura"},
	{"Paita", "Piura"},
	{"Sechura", "Piura"},
	{"Chulucanas", "Piura"},
	{"Lambayeque", "Lambayeque"},
	{"Ferreñafe", "Lambayeque"},
	{"Motupe", "Lambayeque"},
	{"Olmos", "Lambayeque"},
	{"Lamas", "San Martín"},
	{"Juanjuí", "San Martín"},
	{"Huamachuco", "La Libertad"},
	{"Pacasmayo", "La Libertad"},
	{"Chepén", "La Libertad"},
	{"Casma", "Áncash"},
	{"Huarmey", "Áncash"},
	{"Caraz", "Áncash"},
	{"Yungay", "Áncash"},
	{"Desaguadero", "Puno"},
	{"Ilave", "Puno"},
	{"Ayaviri", "Puno"},

	// Distritos de Lima Metropolitana
	{"Miraflores", "Lima"},
	{"San Isidro", "Lima"},
	{"Barranco", "Lima"},
	{"Santiago de Surco", "Lima"},
	{"San Borja", "Lima"},
	{"La Molina", "Lima"},
	{"Surquillo", "Lima"},
	{"Chorrillos", "Lima"},
	{"San Miguel", "Lima"},
	{"Magdalena del Mar", "Lima"},
	{"Jesús María", "Lima"},
	{"Lince", "Lima"},
	{"Pueblo Libre", "Lima"},
	{"Breña", "Lima"},
	{"La Victoria", "Lima"},
	{"Rímac", "Lima"},
	{"San Juan de Lurigancho", "Lima"},
	{"San Juan de Miraflores", "Lima"},
	{"Villa El Salvador", "Lima"},
	{"Villa María del Triunfo", "Lima"},
	{"Comas", "Lima"},
	{"Los Olivos", "Lima"},
	{"San Martín de Porres", "Lima"},
	{"Independencia", "Lima"},
	{"Ate", "Lima"},
	{"Santa Anita", "Lima"},
	{"El Agustino", "Lima"},
	{"Lurín", "Lima"},
	{"Pachacámac", "Lima"},
	{"Carabayllo", "Lima"},
	{"Puente Piedra", "Lima"},
	{"Cieneguilla", "Lima"},
	{"San Luis", "Lima"},

	// Provincia Constitucional del Callao
	{"Callao", "Callao"},
	{"Bellavista", "Callao"},
	{"La Perla", "Callao"},
	{"La Punta", "Callao"},
	{"Ventanilla", "Callao"},
	{"Carmen de la Legua", "Callao"},
}

// DepartamentosPeru son los 24 departamentos del Perú más la Provincia
// Constitucional del Callao. Se añaden como lugares para que también aparezcan
// en el autocompletado.
var DepartamentosPeru = []Ciudad{
	{"Amazonas", "Amazonas"},
	{"Áncash", "Áncash"},
	{"Apurímac", "Apurímac"},
	{"Arequipa", "Arequipa"},
	{"Ayacucho", "Ayacucho"},
	{"Cajamarca", "Cajamarca"},
	{"Callao", "Callao"},
	{"Cusco", "Cusco"},
	{"Huancavelica", "Huancavelica"},
	{"Huánuco", "Huánuco"},
	{"Ica", "Ica"},
	{"Junín", "Junín"},
	{"La Libertad", "La Libertad"},
	{"Lambayeque", "Lambayeque"},
	{"Lima", "Lima"},
	{"Loreto", "Loreto"},
	{"Madre de Dios", "Madre de Dios"},
	{"Moquegua", "Moquegua"},
	{"Pasco", "Pasco"},
	{"Piura", "Piura"},
	{"Puno", "Puno"},
	{"San Martín", "San Martín"},
	{"Tacna", "Tacna"},
	{"Tumbes", "Tumbes"},
	{"Ucayali", "Ucayali"},
}

// Dataset devuelve el conjunto completo de lugares a cargar en la base de datos:
// ciudades/distritos y departamentos. Las repeticiones (una capital que también
// es departamento) se ignoran al insertar gracias a la restricción UNIQUE.
func Dataset() []Ciudad {
	completo := make([]Ciudad, 0, len(CiudadesPeru)+len(DepartamentosPeru))
	completo = append(completo, CiudadesPeru...)
	completo = append(completo, DepartamentosPeru...)
	return completo
}
